import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import { AuthContextProvider } from './context/authContext'
import Footer from './components/Footer'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Rios Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <Navbar />
          <div className='h-[6rem]'/>
          {children}
          <Footer />
        </AuthContextProvider>
        <ToastContainer
            position='bottom-right'
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme='colored'
        />
      </body>
    </html>
  )
}
